# Generated by Django 5.1.1 on 2024-10-11 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_comment_text_comment_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
